# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrations',
            fields=[
                ('drugs_id', models.AutoField(primary_key=True, serialize=False, verbose_name='药品编号')),
                ('drugs_name', models.CharField(max_length=50, verbose_name='药品名称')),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='药品条码')),
                ('or_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='药品二维码')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('mnemonic', models.CharField(blank=True, max_length=50, null=True, verbose_name='助记码')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('register_code', models.CharField(max_length=50, verbose_name='登记证号')),
                ('stock_count', models.CharField(max_length=50, verbose_name='库存数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '药品管理',
                'verbose_name_plural': '药品管理',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('drugs_id', models.AutoField(primary_key=True, serialize=False, verbose_name='药品编码')),
                ('drugs_name', models.CharField(max_length=50, verbose_name='药品名称')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='administration.Category')),
            ],
            options={
                'verbose_name': '药品类别',
                'verbose_name_plural': '药品类别',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False, verbose_name='计量编码')),
                ('metering_name', models.CharField(max_length=50, verbose_name='计量名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '计量单位',
                'verbose_name_plural': '计量单位',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50, verbose_name='地区名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='销售编号')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('register_code', models.CharField(max_length=50, verbose_name='登记证号')),
                ('customer_name', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('customer_tel', models.CharField(max_length=50, verbose_name='客户电话')),
                ('customer_address', models.CharField(max_length=50, verbose_name='客户地址')),
                ('sale_count', models.CharField(max_length=50, verbose_name='销售数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位编码')),
                ('drugs_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Administrations', verbose_name='药品名称')),
                ('input_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人员')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Measurement', verbose_name='计量单位')),
            ],
            options={
                'verbose_name': '药品销售',
                'verbose_name_plural': '药品销售',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.AutoField(primary_key=True, serialize=False, verbose_name='入库编号')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('register_code', models.CharField(max_length=50, verbose_name='登记证号')),
                ('stock_count', models.CharField(max_length=50, verbose_name='采购数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位编码')),
                ('drugs_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Administrations', verbose_name='药品名称')),
                ('input_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人员')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Measurement', verbose_name='计量单位')),
            ],
            options={
                'verbose_name': '药品入库',
                'verbose_name_plural': '药品入库',
            },
        ),
        migrations.AddField(
            model_name='administrations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Category', verbose_name='药品类别'),
        ),
        migrations.AddField(
            model_name='administrations',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位编码'),
        ),
        migrations.AddField(
            model_name='administrations',
            name='input_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人员'),
        ),
        migrations.AddField(
            model_name='administrations',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Measurement', verbose_name='计量单位'),
        ),
    ]
