# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='药品类别')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='administration.Category', verbose_name='父类')),
            ],
            options={
                'verbose_name': '药品类别',
                'verbose_name_plural': '药品类别',
            },
        ),
        migrations.CreateModel(
            name='DrugPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('register_code', models.CharField(max_length=50, verbose_name='登记证号')),
                ('purchase_count', models.IntegerField(verbose_name='采购数量')),
                ('update_time', models.DateField(verbose_name='采购时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '药品采购',
                'verbose_name_plural': '药品采购',
            },
        ),
        migrations.CreateModel(
            name='DrugSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('register_code', models.CharField(max_length=50, verbose_name='登记证号')),
                ('customer_name', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('customer_tel', models.CharField(max_length=50, verbose_name='客户电话')),
                ('customer_address', models.CharField(max_length=50, verbose_name='客户地址')),
                ('sale_count', models.IntegerField(default=0, verbose_name='销售数量')),
                ('update_time', models.DateField(verbose_name='销售时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '药品销售',
                'verbose_name_plural': '药品销售',
            },
        ),
        migrations.CreateModel(
            name='DrugStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='药品名称')),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='药品条码')),
                ('or_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='药品二维码')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('help_word', models.CharField(blank=True, max_length=50, null=True, verbose_name='助记码')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('register_code', models.CharField(max_length=50, verbose_name='登记证号')),
                ('stock_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='库存数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Category', verbose_name='药品类别')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位编码')),
                ('input_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人员')),
            ],
            options={
                'verbose_name': '药品库存',
                'verbose_name_plural': '药品库存',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='地区名称')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='计量名称')),
            ],
            options={
                'verbose_name': '计量单位',
                'verbose_name_plural': '计量单位',
            },
        ),
        migrations.AddField(
            model_name='drugstock',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Unit', verbose_name='计量单位'),
        ),
        migrations.AddField(
            model_name='drugsale',
            name='drugs_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DrugStock', verbose_name='药品名称'),
        ),
        migrations.AddField(
            model_name='drugsale',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位编码'),
        ),
        migrations.AddField(
            model_name='drugsale',
            name='input_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人员'),
        ),
        migrations.AddField(
            model_name='drugsale',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Unit', verbose_name='计量单位'),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='drugs_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.DrugStock', verbose_name='药品名称'),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位编码'),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='input_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录入人员'),
        ),
        migrations.AddField(
            model_name='drugpurchase',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Unit', verbose_name='计量单位'),
        ),
    ]
